### ISSUE TITLE
How to work with chromium browser in ubuntu?

### ISSUE THREAD

**Issue by hungchai** [phantombuster/nickjs#10]
In ubuntu Server, there is not chrome instead of chromium. Is it the same way to set the chromium path to Chrome_Path environment variable?

**Comment by paps** [comment]
NickJS should work with Chromium without any issues. Did you try setting `CHROME_PATH` to `/usr/bin/chromium-browser`?

**Comment by hungchai** [comment]
Thanks @paps . Actually, I am still comparing this library with puppeteer.  The LTS is my main consideration.
Secondly, I believe most of ppl will use chrome/chomium instead of phantomjs. 
Why don't install the headless chrome together? just like puppeteer. It will be more convenience.

**Comment by paps** [comment]
I see what you mean, it would be great to not have to think about Chrome's location.

However NickJS aims to support an arbitrary number of headless browser drivers. Today we support PhantomJS+CasperJS and Headless Chrome, but anyone could add another (like Firefox which has a new headless mode now, or even WebDriver).

For this reason, we don't include the driver's binaries. `npm install nickjs` should not install 100mb+ of headless browsers... Do you have an idea on how we could fix this problem?

**Comment by hungchai** [comment]
In my point of view, this library should include one browser binary default whether phantomjs or chrome is not a problem. Because this library is a general interface to remote the multi-brand browsers, so you at least include one browser to let developers has a quick start environment.
The `chrome_path` is a flexible and great setting for advanced developers.
