### ISSUE TITLE
Dockerise NickJs (Latest version)

### ISSUE THREAD

**Issue by clementvp** [phantombuster/nickjs#11]
Hi.
Do you have an image to dockerize nickjs (latest version with chrome) ?
I tried to dockerize my app with a very simple dockerfile with the latest node image
 
```
FROM node:latest
ADD ./app /app
WORKDIR /app
ENV CHROME_PATH=/usr/bin/google-chrome
RUN apt-get update && install google-chrome-stable
RUN npm install
CMD npm start
```
My app it's your example with ycombinator and nothing more.
The google-chrome-stable version is 62 (in accordance with your documentation).

The image build is ok, chrome's installation is ok path is ok (Check with `which google-crome` and `echo "$CHROME_PATH"`).
But when i run a new container or when i run `node index.js` to launch my node script inside a new container i got this error:

`Fatal: Chrome subprocess exited with code 1`

And i can't figured out what is my problem.

**Comment by paps** [comment]
Can you try with `NICKJS_NO_SANDBOX` env variable set to `1`?

**Comment by clementvp** [comment]
Yep that was that. :)
I was unaware google-chrome can't be launch with root in container. My bad.
Thank you very much.

**Comment by paps** [comment]
No worries :)

I don't think the problem is root or anything. It's more like Chrome trying to build its own sandbox with cgroups etc, while at the same time already being in the Docker sandbox. Apparently having a sandbox inside a sandbox is not so easy.

**Comment by clementvp** [comment]
I tried to create a user and run my script with this user inside my container and everything work. (without ENV NICKJS_NO_SANDBOX=1 in my docker file)

And if I tried to launch google-chrome with root I have:
`Running as root without --no-sandbox is not supported. See https://crbug.com/638180.`

Anyway, it's work, i'm happy :)
Thank again.
