### ISSUE TITLE
Client Request / Server Response Headers

### ISSUE THREAD

**Issue by mojopollo** [phantombuster/nickjs#12]
Is there a way to log/view the client request headers and the server response headers?

**Comment by paps** [comment]
Yes, like this:

	tab.driver.client.Network.requestWillBeSent((e) => {
		console.log(`-=>> requestWillBeSent: ${e.request.method} (${e.request.postData ? `sending ${e.request.postData.length} bytes` : "no post data"}) ${e.request.url}`)
	})
	tab.driver.client.Network.responseReceived((e) => {
		console.log(` <<=- responseReceived: ${e.response.status} (type: ${e.type}, frameId: ${e.frameId}, loaderId: ${e.loaderId}) ${e.response.url}`)
	})

This is sample code, it's only logging a few of all the available fields.

**Comment by mojopollo** [comment]
Very cool, thank you !
