### ISSUE TITLE
Change Proxy and User-Agent after Nick instantiation 

### ISSUE THREAD

**Issue by mojopollo** [phantombuster/nickjs#13]
What would be the best way to set a different proxy and user-agent on each tab open, testing this out currently but not sure if this is the right approach:

```
const nick = new Nick({
  printNavigation: true,
  printResourceErrors: true,
  printPageErrors: false,
  resourceTimeout: 10000,
})

// start loop logic

;(async () => {
        nick.options.userAgent = randomUserAgent;
        nick.options.httpProxy = randomProxy;

        const tab = await nick.newTab()
        await tab.open(url)

        // Clean up
        await nick.deleteAllCookies()
        await tab.close()
})()

// end loop logic
```

Initially I had const nick = new Nick inside my loop logic and that crashed node after 100 tab opens, pretty sure why :)

**Comment by paps** [comment]
I don't think setting a proxy per tab (target) is supported yet by Headless Chrome (or Chrome for that matter). You can however set different authentication per request, but it's not useful in your case, right?

When you set the `httpProxy` option, NickJS sets the `--proxy-server` flag on the Chrome binary and adds authentication info to requests, that's it. So you cannot set multiple proxies yet!

---

If you're talking about the CasperJS+PhantomJS driver, then you can set the proxy with `tab.driver.page.setProxy()` see here https://github.com/ariya/phantomjs/issues/14157

**Comment by mojopollo** [comment]
Right, what I should have mentioned is that I wanted to (per session)
1. instantiate nick with a selected proxy & user-agent
2. open url (which will use the proxy & user agent)
3. close nick or clear out any session based cookies/proxy/user-agent
4. set a new proxy & user-agent
5. open a 2nd url (which will use a different proxy & user agent)
and so on (using a different proxy)

I did some testing and I ended up just creating a BASH script that just loops `node mytest.js`, this allows me to set a different proxy & user-agent on each session. Initially I was looking for a way to do this without the use of the bash script.

**Comment by paps** [comment]
Multiple instances of NickJS running at the same time is not something that's supported at this time.

We made the design choice to use tabs for that, with the shortcomings that come with it, for example your problem of single proxy per NickJS instance.

I'm closing the issue because you seem to have found a solution, but feel free to re-open it if necessary :)

**Comment by mohammad-rj** [comment]
Would you please! Make an example of this
Multiple instances
with different
proxy and user agent 
per each one
