### ISSUE TITLE
can nickjs open a chrome window like {headless:false} do in puppeteer?

### ISSUE THREAD

**Issue by jiji262** [phantombuster/nickjs#14]

**Comment by SaShimy** [comment]
Hi @jiji262 , there isn't this feature built in nickjs but you can launch a script and then connect to 127.0.0.1:9222 with your browser to connect to the debugger.
![chromedebugger](https://user-images.githubusercontent.com/10746385/33031656-359720b4-ce1f-11e7-99f3-a47fb8837525.png)
Just click the link on this page after launching your script.

**Comment by paps** [comment]
Hey @jiji262 

The newest version, 0.2.4, has the flag now. Happy scraping :)
