### ISSUE TITLE
Any advice for deploying on Heroku?

### ISSUE THREAD

**Issue by wbelk** [phantombuster/nickjs#15]
I've run `heroku buildpacks:add https://github.com/heroku/heroku-buildpack-google-chrome` and rooting around on the forums but not having much luck.

Seems like I'm heading in the right direction:

<img width="747" alt="screen shot 2017-11-24 at 5 31 32 pm" src="https://user-images.githubusercontent.com/271844/33226221-a42eb976-d13d-11e7-93f0-f462eda37549.png">

**Comment by paps** [comment]
I have zero experience with Heroku, sorry!

But if you can have Google Chrome installed, I don't see any reason for it not to work. The next step would be to `npm install nickjs` and set `CHROME_PATH` to the correct value. Maybe also set `NICKJS_NO_SANDBOX` to `1` if Chrome does not start?

**Comment by wbelk** [comment]
Ok so I have no idea the order in which these where successful, but I got it working with the following:
heroku buildpacks:add https://github.com/heroku/heroku-buildpack-google-chrome

heroku create --buildpack https://github.com/heroku/heroku-buildpack-chromedriver.git

<img width="826" alt="screen shot 2017-11-25 at 7 52 11 am" src="https://user-images.githubusercontent.com/271844/33232154-d62a9bd4-d1b5-11e7-8489-eb28119a56c2.png">

**Comment by dapperjapper** [comment]
For posterity: all I needed to do was
```
heroku buildpacks:add https://github.com/heroku/heroku-buildpack-google-chrome
```
And at the top of my scraper script:
```js
process.env.CHROME_PATH = process.env.GOOGLE_CHROME_SHIM || require('puppeteer').executablePath()
```
`GOOGLE_CHROME_SHIM` is a variable from the buildpack. I'm using the puppeteer binary as a fallback for local development. (I hope this is wise? I'm new to this and unsure how to replicate the production setup on my local machine)

**Comment by paps** [comment]
Thanks for the details @dapperjapper :) We see more and more people running NickJS on heroku, so it's useful!
