### ISSUE TITLE
Allow changing NickJS options after the initial constructor

### ISSUE THREAD

**Issue by Leftium** [phantombuster/nickjs#17]
Please enable changing NickJS options after the initial constructor. Specifically, I would like to modify:

- `loadImages` flag
- blacklist/whitelist
- (and the `print*` flags would be nice, too)

**Motivation:** I would like to use a special configuration just when logging in

- Login page requires `loadImages=true` and no blacklists
- but other pages are OK with `loadImages=false` and blacklists (and load faster without images & JS files)

**Comment by paps** [comment]
Hi Leftium, sorry for the delay.

This is not officially supported but you can do `nick.options.loadImages = false` and similar. This will only work on new tabs, so close your tab with `tab.close()` and open a new one. It should use the new options. Don't worry, cookies are kept between tabs.

Can you confirm this works? Thanks
