### ISSUE TITLE
Phantom.js + casper : syntaxError: Unexpected token '>'

### ISSUE THREAD

**Issue by Antoinebr** [phantombuster/nickjs#18]
When I try to launch the example I get this error : 

```
SyntaxError: Unexpected token '>'

  phantomjs://code/test.js:4 in injectJs
  phantomjs://code/bootstrap.js:456

```

To launch the script I use : 

```
node_modules/casperjs/bin/casperjs test.js
```

test.js contains the example from readme.md 

EDIT : 

I just discoered that casper.js or phantom is not suporting ES6 

```JavaScript 
setTimeout( () =>  console.log('Hello'), 3000 );
```

this fail :'(

**Comment by SaShimy** [comment]
Hi @Antoinebr ,
Yes Casperjs and Phantomjs doesn't support ES6 syntax but you use babel following this [guide](https://github.com/phantombuster/nickjs/blob/master/PHANTOMJS.md) if you want the best of both worlds. Although I recommend to use HeadlessChrome.

Enjoy using NickJS 👍 

Regards,

**Comment by Antoinebr** [comment]
Hi SaShimy  thanks for your answer. 

I got a lot of issues by using Chrome ( most of the the time nicks js can't contact Chrome) 

I just found a solution I used your docker image https://hub.docker.com/r/sashimy/nickjs-techio/ 

And I made couple of adjustement : 

build-launch.sh :
````

#!/usr/bin/env bash

npm run build

./node_modules/.bin/babel ./lib/nick.js > ./lib/build.js 

./node_modules/casperjs/bin/casperjs ./lib/build.js

``` 

To run the docker image 

```
docker run -it -v  ./:/project/target/lib/  nick.js_build bash  

```  


Also I got an error with babel : 

babel TypeError: Object is not a constructor 

I replaced 

```JavaScript 
const Nick = require('nickjs')
```

with  : 

```JavaScript 

const Nick = require('nickjs').default;

```

And now it's working 👍
