### ISSUE TITLE
How to use Node API (Or How to export results as file)

### ISSUE THREAD

**Issue by clementvp** [phantombuster/nickjs#2]
Hi, it's me Again.
It sound dumb (and not really relative to nick) but how can i use Node API like fs (for writing my scrapping results in a json file) ?
Here my code 
```
require('babel-polyfill')
const Nick = require('nickjs')
const nick = new Nick()
var fs = require('fs');
nick.newTab().then(async function (tab) {
  await tab.open('http://example.com')
  await tab.waitUntilVisible('.products-grid')
  await tab.inject('./jquery.js')
  const urls = await tab.evaluate((arg, callback) => {
    const urls = []
    $("li.item").each((index, element) => {
      urls.push($(element).find("div.product-content-wrapper").find('h3.product-name').find('a').attr('href'))
    })
    callback(null, urls)
  })
  var data = []
  for (var i = 0; i < urls.length; i++) {
    await tab.open(urls[i])
    await tab.waitUntilVisible('.catalog-product-view')
    await tab.inject('./jquery.js')
    const type = await tab.evaluate((arg, callback) => {
      var type = $('div.product-name').find('h1').text()
      callback(null, type)
    })
    const img = await tab.evaluate((arg, callback) => {
      var img = $('div#map_container').find('img').attr('src')
      callback(null, img)
    })
    data.push({ type: type, img: img })    
    await tab.screenshot('./uploads/' + i + '.png')
  }
  fs.writeFile('./myjsonfile.json', data, 'utf8', ()=>{
    nick.exit()
  });  
}).catch((err) => {
  console.log('Oops, an error occurred: ' + err)
  nick.exit(1)
})

```
Here at the end I want to write a json file with my results (var data is an Object).
But in the execution i have an error

undefined is not a function (evaluating 'fs.writeFile('./myjson.json', data, function () {

})')

For my defense, i'm really new to PhantomJs/CasperJs and Babel.
I know my script is executed in a CasperJS context, but i can't figured out why i can't use fs (even with the require('babel-polyfill')

Anyone to help me learn and make me a better dev ?

**Comment by clementvp** [comment]
Ho ! 
I think i figured out:
[http://phantomjs.org/api/fs/method/write.html](url)

It's sound like the fs Node API but it's not. I was unaware of that, my bad.
it's the fs = require('fs'), that's trouble me.

I'm now able to write a json file with this code 
``
await fs.write('./mydata.json', JSON.stringify(data), 'w')
``
But i resolve just a part of my question. Now, if i want to use a npm package or a Node Api like Crypto, how can i do that ?
I really like this package : [https://www.npmjs.com/package/jsonfile](url)

**Comment by SaShimy** [comment]
Hi @clementvp ,
First of all I have to ask you where are you executing nickjs to better understand your problem but from what I can tell you are using casperjs/phantomjs so 'fs' is not the same in phantomjs that the 'fs' from nodejs. You can have more informations [here](http://phantomjs.org/api/fs/) and if you want a better support (live and with many people) I recommend you to go on our gitter -> [here](https://gitter.im/phantombuster/nickjs) so we can have a talk and help you better understand nickjs.

I hope this will help you enjoy nickjs !

Have a great day

**Comment by clementvp** [comment]
Thanks @SaShimy 
I will join your gitter and i will stop annoying you in the repo issues ;)
Thanks again.

**Comment by SaShimy** [comment]
Don't worry, I am not annoyed at all rather excited by the first issues issued to nickjs repo :)
