### ISSUE TITLE
Error: failed to inject local script "../injectables/jquery.min.js"

### ISSUE THREAD

**Issue by sulthonzh** [phantombuster/nickjs#20]
how solvethis error :
when run with thiscommand

`./node_modules/casperjs/bin/casperjs lib/myNewBot.js`

**Comment by paps** [comment]
You should replace `"../injectables/jquery.min.js"` with a path to an existing jQuery file. It can also be an URL, `"https://code.jquery.com/jquery-3.2.1.min.js"` will most certainly work.

**Comment by sulthonzh** [comment]
![2018-01-05-172908_1366x768_scrot](https://user-images.githubusercontent.com/4921059/34605528-8b44c4ec-f23e-11e7-84dc-ada4a8248f10.png)
why this is give me same error?

run from `casperjs`

**Comment by paps** [comment]
That's weird. Can you try adding `--web-security=false` between the casperjs binary and your script? Are you using a proxy?

**Comment by sulthonzh** [comment]
not using proxy, tried `--web-security=false` but not effect, how about local lib *.js, where is right path to store injections lib? like my SS, Right?

**Comment by paps** [comment]
The path is relative to your working directory. Maybe try puttin `jquery.js` in the same folder?
