### ISSUE TITLE
NickJS is making partial page screenshots instead of full page screenshots

### ISSUE THREAD

**Issue by man0l** [phantombuster/nickjs#22]
Hi dev team, 
It seems the headless chrome remote interface can make full page screenshots, by setting the right resolution in Emulation.setVisibleSize

I wasn't able to find such option in Nickjs, and I am getting the half of the screenshot:

![cycle_invoices_1](https://user-images.githubusercontent.com/1413216/34865763-997c39de-f782-11e7-8bf4-495474fe6cc3.png)

What would you recommend?

**Comment by paps** [comment]
Hey @man0l 

Sorry for the delay

This was fixed by https://github.com/phantombuster/nickjs/commit/66c7bf2fd9e26c085b4c832e67abf9d4a3601d78, released in v0.3.2. NickJS now always takes full page screenshots.

**Comment by man0l** [comment]
Thank you, this is great feature! I will update my nickjs to the current version.

I have solved partially the issue with setting the resolution directly to the headless chrome with passing this parameter: --window-size=1280x720. It could be usefull for someone within the nickjs community.

Thank you again and regards,
Manol.
