### ISSUE TITLE
Filling a value in textarea

### ISSUE THREAD

**Issue by jprrabanal** [phantombuster/nickjs#28]
How do you insert a text inside a textarea that is not belongs to a form tag?

**Comment by jprrabanal** [comment]
nvm, i found out that we should use sendKeys.

**Comment by paps** [comment]
Glad you figured it out :)

Another way of doing it is injecting jQuery if necessary (`tab.inject()`), then `tab.evaluate()` of `$('#field').val('your text')`

**Comment by jprrabanal** [comment]
@paps Awesome, Thanks!
