### ISSUE TITLE
Using google-chrome-unstable ??

### ISSUE THREAD

**Issue by savethedave** [phantombuster/nickjs#29]
Need some help getting Chrome running in different environments.

In a different thread, you said nickjs looks for google-chrome-unstable before checking CHROME_PATH in environment variables.

Is using google-chrome-unstable the best way to have the same code execute in both a local (Mac) and remote (EC2/Elastic Beanstalk) node.js setup?

If so, can you help with download/install instructions of google-chrome-unstable?

If not, can you provide help with getting nickjs to recognize Chrome in an EC2 instance?

Thx - I know these are probably noob questions.

**Comment by paps** [comment]
Hi, any version of Chrome above 63 will work, so you're okay with Chrome stable, beta and dev.

Simply set the CHROME_PATH env var to the correct path where your local Chrome binary is. On your mac it will be something like `"/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"` whereas on EC2 it will be more like `"/usr/bin/google-chrome"` (I can't say exactly, it totally depends on which OS, distribution and package you install. I suggest you use the recommended installation procedure for your chosen distribution, typically `apt-get install ` on Debian or Debian-based distribs.)

If you want more details on Chrome installation, check out their official documentation here https://www.chromium.org/getting-involved/dev-channel

**Comment by savethedave** [comment]
Thx.
