### ISSUE TITLE
Simulate a Enter event

### ISSUE THREAD

**Issue by jprrabanal** [phantombuster/nickjs#30]
How do i simulate a Enter event, like pressing enter after sending keys in a textarea?

**Comment by paps** [comment]
Funny you're asking this now, we just discussed this last week with the team.

It turns out that putting `\r` in your `sendKeys()` string will send an Enter key press.

**Comment by paps** [comment]
Behind the scenes it's calling the DevTools `dispatchKeyEvent` (https://chromedevtools.github.io/devtools-protocol/tot/Input#method-dispatchKeyEvent) which is, I think, sending real key presses. Not 100% sure though.
