### ISSUE TITLE
Possible support for mouse simulations?

### ISSUE THREAD

**Issue by jprrabanal** [phantombuster/nickjs#32]
Is there a possible future support for mouse simulations?

**Comment by paps** [comment]
Yes in the future we might support mouse events, more than just the `tab.click()` method anyway. I don't have an ETA though, sorry.

In the meantime you can go down an abstraction layer and make direct calls to the `dispatchMouseEvent` DevTools method, like so: `await tab.driver.client.Input.dispatchMouseEvent({ ... options ... })`. Documentation is here: https://chromedevtools.github.io/devtools-protocol/tot/Input#method-dispatchMouseEvent
