### ISSUE TITLE
Use Proxy

### ISSUE THREAD

**Issue by hugsbrugs** [phantombuster/nickjs#4]
Hi !

I begin using your lib and I'm wondering if and how I could use proxy to connect to the web ?

thanks for your work

Hugo

**Comment by paps** [comment]
Hey, support for proxies is coming in a few days, stay tuned :)

**Comment by paps** [comment]
Hey support for proxies is live since 0.2.0 (17770004479c0a1ac5846932255162a699343146)

See readme for details. Closing!

**Comment by hugsbrugs** [comment]
Nice but I don't see how you can use a password protected proxy since from my searches chromium does not allow a user/pass for proxy. I had to use https://github.com/sjitech/proxy-login-automator to locally proxy my request. I will test and have a look at your code if it works with authentication ;)

**Comment by paps** [comment]
It does work with authentication. I made sure of that :)
