### ISSUE TITLE
About sendKeys()

### ISSUE THREAD

**Issue by msaus** [phantombuster/nickjs#45]
Hello there,

Is reset option working?

I found that it is not working and so the previous value is left in the input box.

Here is my code.
> await tab.sendKeys('#username', id, {reset:true,keepForcus:false});

Can you confirm that?

OS: Ubuntu 16.04
NickJS: The latest one
Google Chrome: 67.0.3396.62 

Best regards,

**Comment by paps** [comment]
Hi, yes, `reset` is ignored in the case of the Chrome driver. Sorry about that, the documentation is confusing (not to say, totally wrong).

What you can do is clear the field beforehand with an `evaluate()` call. Does that make sense?

**Comment by msaus** [comment]
Thanks for quick response.

I see.

Do you think you will fix it up in the future?

If not then, I will use evaluate to clear the input.

regards,

**Comment by paps** [comment]
Great, you got it working? Re-open if not :)
