### ISSUE TITLE
Execution context when calling an evaluate

### ISSUE THREAD

**Issue by jprrabanal** [phantombuster/nickjs#50]
Does the evaluate function include all the execution context in the page? Like the elements in an iframe

[https://stackoverflow.com/questions/48776320/iframes-document-selectors-return-null-in-devtools-console-but-then-return-ele](url)

**Comment by jprrabanal** [comment]
Accessed the iframe using HTMLIFrameElement.contentWindow.

**Comment by paps** [comment]
Nice 👍
