### ISSUE TITLE
Is it possible to change userAgent?

### ISSUE THREAD

**Issue by msaus** [phantombuster/nickjs#51]
Hello there,

I would like to change userAgent after initialization of Ncickjs.

What I found is following.

> tab = await nick.newTab(); 
> tab.driver.client.Network.setUserAgentOverride({"userAgent":userAgent});

Is this correct way to do?

regards,

**Comment by paps** [comment]
No need to go down to the driver level. Simply use the `userAgent` initialization parameter

https://hub.phantombuster.com/reference#nick

Cheers
