### ISSUE TITLE
Independent tabs with PhantomJS

### ISSUE THREAD

**Issue by JutGreg** [phantombuster/nickjs#56]
Hey everyone, is it possible to use independent tabs with PhantomJS? I mean when I open them, I grab a fresh cache, and everytime I close the tab, the cookies will be automatically delete

Also while using multiple tabs, they wouldn't share the same cache.

Thanks for the help.

**Comment by paps** [comment]
Hey,

Using multiple tabs, you won't be able to prevent cache sharing between them. If you use one tab at a time, you can clear the cache between each use, for example with PhantomJS (CasperJS) you can do `nick.driver.casper.page.clearMemoryCache()`.

A solution would be to start multiple NickJS instances, independent of each other. (That is, one PhantomJS instance per tab)

Please note that PhantomJS/CasperJS are deprecated projects.
