### ISSUE TITLE
I have a question for many requests

### ISSUE THREAD

**Issue by msaus** [phantombuster/nickjs#57]
Hello,

Do you use docker for many requests?

For example, do you create multiple docker instances in 1 server and handle many requests?

Best regards,

**Comment by paps** [comment]
Hey,

Yes, that's basically what our service Phantombuster does. We have a cluster of servers that each have a docker deamon and load balancing / management code to handle everything.

Regards

**Comment by msaus** [comment]
Tello there,

Thanks for that.

**Comment by paps** [comment]
In production we use AWS ALB to load balance incoming requests. Then we have a custom made load balancer to select the correct VM in which to launch a new docker container with Chrome inside.
