### ISSUE TITLE
 getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by chenhm123** [phantombuster/nickjs#6]
hi , when i run the demo, it appears Error: getaddrinfo ENOTFOUND localhost undefined:9222

**Comment by chenhm123** [comment]
so bad

**Comment by paps** [comment]
Can you please describe with more detail the steps needed to trigger this error?

**Comment by chenhm123** [comment]
well.when i run the demo in the company ,the console appears
`Something went wrong: could not connect to chrome debugger after 40 tries (10s): Error: getaddrinfo ENOTFOUND localhost undefined:9222`
then i think it's port(9222) needs  add  'sudo' to execute.but it doesn't work.. it appears 
`Something went wrong: could not start chrome: Error: spawn google-chrome-unstable ENOENT`

however ,  i  run it at home , it works well now
maybe something wrong with network

**Comment by chenhm123** [comment]
sorry..my english is very poor
i want to set up a automate test platform,  i had use phantomjs-node complete a little of work, but it's very unusefulness .. today i find casperjs and your nickjs ,,i think nickjs is friendlier

**Comment by paps** [comment]
Ok thanks. I think the problem might come from your CHROME_PATH environment variable. You have to set this to the exact path of your Google Chrome binary, for example something like `/Applications/Google Chrome.app/Contents/MacOS/Google Chrome` if you're using macOS.

**Comment by chenhm123** [comment]
no, no ~
i find the problem today,  because my mac uses Cable adapter for network, i think it change the ip, result in the server go wrong
