### ISSUE TITLE
Setting environment variables on PHP / Ubuntu

### ISSUE THREAD

**Issue by yazer79** [phantombuster/nickjs#64]
NickJs runs fine on Ubuntu after setting CHROME_PATH manually
`$ export CHROME_PATH=chromium-browser`
 and running node from terminal

However, I can't run it from PHP unless I execute node script from terminal manually. I want PHP to set the environment variables
`putenv('CHROME_PATH=/usr/bin/chromium-browser');`
This is not working. Any suggestions?

**Comment by paps** [comment]
Hi there, can you show what method you're using to start NickJS please?

**Comment by yazer79** [comment]
Hi paps!
`$proc = proc_open('node test.js', $in, $out);`

**Comment by paps** [comment]
One of the parameters of `proc_open` is an array of environment variables to forward to the child process. It should work if you set CHROME_PATH this way.

**Comment by yazer79** [comment]
Can't get it to work yet
```
$in =[];
$out = [];
$env = ["CHROME_PATH"=>"/usr/bin/chromium-browser"];
$cwd = getcwd() ;
$proc = proc_open('node '.$nodeJs,  $in, $out, $cwd, $env);
```

**Comment by yazer79** [comment]
I don't mind using exec() or shell_exec() if they are more simple to follow putenv(). I hope I can learn more than one way

**Comment by paps** [comment]
It's hard to tell what's going on. What error are you getting? I need more info to help :)

**Comment by yazer79** [comment]
Nothing happens at all, nickjs won't start as it can't find chrome, so the script times out. Is there an email to use for support or contact you?

**Comment by yazer79** [comment]
I finally got it!
The env vars were loaded right, but the script was failing silently because of the script saving screenshot had no write permissions and I didn't notice that. Thanks a lot :)

**Comment by paps** [comment]
Nice, glad to hear that :)
