### ISSUE TITLE
Using jQuery instead of querySelector on Tab

### ISSUE THREAD

**Issue by yazer79** [phantombuster/nickjs#65]
Hi!
I am trying to use jQuery in the tab click instead of querySelector, is this possible?
`await tab.click($(div:contains('John'))`
I get
` $ is not defined`
jquery is injected before this click line and working well with the scrape after this

**Comment by paps** [comment]
That is because you're in the node context here. `$` will only be available in an `evaluate()` call (because then the function is sent to chrome to be executed in the page, where `$` was injected)
